### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(Calculator)
add_subdirectory(CalculatorContent)
add_subdirectory(App)
add_subdirectory(Dependencies)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    Calculatorplugin
    CalculatorContentplugin
    QtQuickDesignerComponents)